export const mposts = [
  {
    id: 1,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 2,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 3,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 4,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 5,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 6,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 7,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 8,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 9,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 10,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 11,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 12,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 13,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 14,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 15,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 16,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 17,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 18,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 19,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 20,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 21,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 22,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 23,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 24,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 25,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 26,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 27,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 28,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 29,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 30,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 31,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 32,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 33,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 34,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 35,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 36,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 37,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 38,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 39,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 40,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 41,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 42,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
  {
    id: 43,
    title: "게시글1",
    contents: "게시글 내용게시글 내용게시글 내용",
    writer: "admin",
    insertDate: "2023-07-26",
  },
];
